### PR TITLE
Took the application a step forward : Added Keypress events

### PR DESCRIPTION
**Pull request by kartikeyvaish**
- Added keyboard press events handler
- A little abstraction/code-cleanup
- Comments added (Always a good practice to add comments)

### CODE REVIEW

**Comment by omkar342** [comment]
Thank you so much for your contribution. I will, first of all, understand your code & then I will merge it very soon.

**Comment by kartikeyvaish** [comment]
> Thank you so much for your contribution. I will, first of all, understand your code & then I will merge it very soon.

Yeah, sure. 

- Added keyPress event handler. (You'll love it)
- Added some good coding habits (code-cleanup)

**Comment by kartikeyvaish** [comment]
Any update here @omkar342 ?

**Comment by omkar342** [comment]
Hey, @kartikeyvaish I am sorry for not giving you any update, actually meantime I was improving the front end of this web app & have changed the look of the website a bit. But, Thank you so much for contributing.

**Pull request merged**
